version: '3.4'
services:
  github-webhooks:
    image: jimzucker/github-webhooks:latest
    container_name: github-webhooks
    restart: unless-stopped
    ports:
      - 4567:4567
# you can copy configs locally and then override with:
#  docker cp github-webhooks:/usr/src/app/config .
    volumes:
      - $PWD/webhook_properties:/usr/src/app/.webhook_properties
#      - $PWD/config:/usr/src/app/config
